export interface Recipe {
  id: string;
  slug: string;
  title: string;
  description: string;
  image: string;
  prepTime: string;
  cookTime: string;
  servings: number;
  difficulty: "Easy" | "Medium" | "Hard";
  category: "Quick Meals" | "South Indian" | "Continental" | "Health Bowls" | "Snacks";
  ingredients: string[];
  steps: string[];
  mushroomType: string;
  productSlug: string;
  calories: number;
  protein: string;
}

export const recipes: Recipe[] = [
  {
    id: "r1",
    slug: "garlic-butter-oyster-mushrooms",
    title: "Garlic Butter Oyster Mushrooms",
    description: "Golden-seared oyster mushrooms in a rich garlic butter sauce. Ready in 15 minutes — the perfect weeknight side dish.",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800&auto=format&fit=crop",
    prepTime: "5 min",
    cookTime: "10 min",
    servings: 2,
    difficulty: "Easy",
    category: "Quick Meals",
    ingredients: [
      "250g Premium Oyster Mushrooms",
      "3 tbsp butter",
      "4 cloves garlic, minced",
      "1 tbsp soy sauce",
      "Fresh parsley, chopped",
      "Salt & pepper to taste",
      "Red chili flakes (optional)",
    ],
    steps: [
      "Tear the oyster mushrooms into large pieces along their natural grain.",
      "Heat a wide pan over high heat. Add butter and let it foam.",
      "Add mushrooms in a single layer — don't crowd. Sear without moving for 3-4 minutes until golden.",
      "Flip, cook another 2 minutes. Add garlic and chili flakes, stir for 30 seconds.",
      "Splash in soy sauce, toss to coat. Remove from heat.",
      "Finish with fresh parsley and a crack of black pepper. Serve immediately.",
    ],
    mushroomType: "Oyster",
    productSlug: "premium-oyster-mushroom",
    calories: 180,
    protein: "8g",
  },
  {
    id: "r2",
    slug: "milky-mushroom-curry",
    title: "Milky Mushroom Curry (Kalan Curry)",
    description: "A rich, aromatic South Indian curry with firm milky mushrooms in a coconut-tomato gravy. Perfect with rice or roti.",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=800&auto=format&fit=crop",
    prepTime: "15 min",
    cookTime: "25 min",
    servings: 4,
    difficulty: "Medium",
    category: "South Indian",
    ingredients: [
      "500g Fresh Milky Mushrooms, quartered",
      "2 onions, finely sliced",
      "3 tomatoes, pureed",
      "1/2 cup coconut milk",
      "2 tsp ginger-garlic paste",
      "1 tsp turmeric, 2 tsp coriander powder",
      "1 tsp garam masala, 1 tsp red chili powder",
      "Curry leaves, mustard seeds",
      "2 tbsp coconut oil",
      "Fresh coriander for garnish",
    ],
    steps: [
      "Heat coconut oil. Splutter mustard seeds and curry leaves.",
      "Add sliced onions, sauté until golden brown (8-10 min).",
      "Add ginger-garlic paste, cook for 1 minute until fragrant.",
      "Add tomato puree, turmeric, coriander powder, and chili powder. Cook until oil separates.",
      "Add quartered milky mushrooms. Stir well, cover, and cook for 10 minutes.",
      "Pour in coconut milk, add garam masala. Simmer for 5 minutes.",
      "Garnish with fresh coriander. Serve hot with steamed rice or parotta.",
    ],
    mushroomType: "Milky",
    productSlug: "fresh-milky-mushroom",
    calories: 220,
    protein: "12g",
  },
  {
    id: "r3",
    slug: "mushroom-soup-creamy",
    title: "Creamy Button Mushroom Soup",
    description: "A velvety, restaurant-style mushroom soup with a hint of truffle. Comfort in every spoonful.",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800&auto=format&fit=crop",
    prepTime: "10 min",
    cookTime: "20 min",
    servings: 3,
    difficulty: "Easy",
    category: "Continental",
    ingredients: [
      "400g Organic Button Mushrooms, sliced",
      "1 large onion, diced",
      "3 cloves garlic",
      "2 cups vegetable stock",
      "1/2 cup cream (or cashew cream for vegan)",
      "2 tbsp butter",
      "Fresh thyme, salt, pepper",
      "Truffle oil for finishing (optional)",
    ],
    steps: [
      "Melt butter in a pot. Sauté onion and garlic until soft.",
      "Add sliced button mushrooms, cook on high for 5-7 minutes until browned and liquid evaporates.",
      "Pour in vegetable stock and thyme. Bring to a boil, then simmer 10 minutes.",
      "Blend until silky smooth using an immersion blender.",
      "Stir in cream, season with salt and pepper. Gently reheat.",
      "Ladle into bowls. Drizzle with truffle oil and garnish with sautéed mushroom slices.",
    ],
    mushroomType: "Button",
    productSlug: "organic-button-mushroom",
    calories: 160,
    protein: "6g",
  },
  {
    id: "r4",
    slug: "shiitake-ramen-bowl",
    title: "Shiitake Mushroom Ramen Bowl",
    description: "A warming umami-rich ramen with seared shiitake, soft-boiled egg, and fragrant broth. Restaurant-worthy at home.",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop",
    prepTime: "15 min",
    cookTime: "30 min",
    servings: 2,
    difficulty: "Medium",
    category: "Continental",
    ingredients: [
      "200g Shiitake Exotic Mushrooms",
      "2 packs ramen noodles",
      "4 cups dashi or vegetable broth",
      "2 soft-boiled eggs",
      "2 tbsp miso paste",
      "1 tbsp soy sauce, 1 tbsp mirin",
      "Sesame oil, green onions, nori sheets",
      "Chili oil to taste",
    ],
    steps: [
      "Slice shiitake mushrooms. Sear in sesame oil until crispy-edged. Set aside.",
      "In the same pot, toast garlic and ginger. Pour in broth, bring to simmer.",
      "Whisk in miso paste, soy sauce, and mirin. Keep warm (don't boil).",
      "Cook ramen noodles per package instructions. Drain.",
      "Divide noodles into bowls. Ladle hot broth over.",
      "Top with seared shiitake, halved soft-boiled egg, sliced green onions, nori, and chili oil.",
    ],
    mushroomType: "Shiitake",
    productSlug: "shiitake-exotic",
    calories: 380,
    protein: "18g",
  },
  {
    id: "r5",
    slug: "mushroom-protein-bowl",
    title: "High-Protein Mushroom Power Bowl",
    description: "A nutrient-packed bowl with mixed mushrooms, quinoa, avocado, and a tahini drizzle. Ideal for post-workout meals.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop",
    prepTime: "10 min",
    cookTime: "20 min",
    servings: 2,
    difficulty: "Easy",
    category: "Health Bowls",
    ingredients: [
      "300g Mixed Mushroom Combo Pack",
      "1 cup quinoa, cooked",
      "1 avocado, sliced",
      "Handful of spinach",
      "Cherry tomatoes, halved",
      "2 tbsp tahini + lemon juice dressing",
      "Seeds (pumpkin, sunflower)",
      "Salt, pepper, smoked paprika",
    ],
    steps: [
      "Cook quinoa according to package instructions.",
      "Tear/slice mixed mushrooms. Sear in a hot pan with olive oil and smoked paprika until golden.",
      "Arrange bowls: quinoa base, spinach, seared mushrooms, sliced avocado, cherry tomatoes.",
      "Drizzle with tahini-lemon dressing.",
      "Top with seeds and a crack of black pepper. Serve immediately.",
    ],
    mushroomType: "Mixed",
    productSlug: "mixed-mushroom-combo",
    calories: 420,
    protein: "22g",
  },
  {
    id: "r6",
    slug: "crispy-mushroom-65",
    title: "Crispy Mushroom 65",
    description: "A spicy, crispy South Indian snack that's the perfect party starter. Crunchy outside, juicy inside.",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop",
    prepTime: "20 min",
    cookTime: "15 min",
    servings: 4,
    difficulty: "Medium",
    category: "Snacks",
    ingredients: [
      "500g Organic Button Mushrooms, halved",
      "1 cup rice flour + 2 tbsp corn flour",
      "1 tsp each: chili powder, garam masala, pepper",
      "1/2 tsp turmeric",
      "2 eggs (or gram flour batter for vegan)",
      "Curry leaves, green chilies",
      "Oil for deep frying",
      "Yogurt dip on the side",
    ],
    steps: [
      "Marinate mushroom halves with salt, turmeric, chili powder, and a squeeze of lemon for 15 minutes.",
      "Mix rice flour, corn flour, garam masala, and pepper in a bowl.",
      "Dip marinated mushrooms in beaten egg, then coat generously in flour mixture.",
      "Deep fry in batches at 180°C until golden and crispy (3-4 minutes per batch).",
      "In a separate pan, quickly toss fried mushrooms with curry leaves, slit green chilies, and a pinch of chaat masala.",
      "Serve hot with mint yogurt dip.",
    ],
    mushroomType: "Button",
    productSlug: "organic-button-mushroom",
    calories: 280,
    protein: "10g",
  },
];

export const recipeCategories = ["All", "Quick Meals", "South Indian", "Continental", "Health Bowls", "Snacks"] as const;

export function getRecipeBySlug(slug: string) {
  return recipes.find((r) => r.slug === slug);
}
